times = ("Flamengo", "Palmeiras", "Atlético Mineiro", "Fortaleza", "São Paulo", "Internacional", "Fluminense", "Ceará", "Athletico Paranaense", "Santos", "Corinthians", "Juventude", "Atlético Goianiense", "América Mineiro", "Sport Recife", "Grêmio", "Chapecoense", "Bahia", "Cuiabá", "Red Bull Bragantino")
print("-="*20)
print(f"Lista de times do Brasileirão: {times}")
print("-="*20)
print(f"Os 5 primeiros são {times[0:5]}")
print("-="*20)
print(f"Os 4 últimos são {times[-4:]}")
print("-="*20)
print(f"Times em ordem alfabética: {sorted(times)}")
print("-="*20)
print(f"O {times[16]} está na {times.index('Chapecoense')+1}° posição")